use strikers;
INSERT INTO strikes (`name`, `power`, `speed`, `strike_type`, `video_url_tutorial`, `video_url_fighter`) VALUES ("Jab", "★★☆☆☆", "★★★★★", "Punch","https://www.youtube.com/embed/FSVcmMd9bR4?si=QenoTqpPoH40sTmY", "https://www.youtube.com/embed/INxfWQrToPY?si=H0qxKL7FJYKiZk0x");
INSERT INTO strikes (`name`, `power`, `speed`, `strike_type`, `video_url_tutorial`, `video_url_fighter`) VALUES ("Cross", "★★★★☆", "★★★☆☆", "Punch", "https://www.youtube.com/embed/sK-6Ujp3KYY?si=Hq8Releqxy3YoitC", "https://www.youtube.com/embed/RfsuIEJzRac?si=JE-3_rrDKMSZ2DoD");
INSERT INTO strikes (`name`, `power`, `speed`, `strike_type`, `video_url_tutorial`, `video_url_fighter`) VALUES ("Left Hook", "★★★★☆", "★★★☆☆", "Punch", "https://www.youtube.com/embed/sPkF-Oj3FBU?si=nE-9V2qfuIH_L4DF", "https://www.youtube.com/embed/U_SgSeGw7xA?si=IqLdMiMB-cnYbhWv");
INSERT INTO strikes (`name`, `power`, `speed`, `strike_type`, `video_url_tutorial`, `video_url_fighter`) VALUES ("Overhand Right", "★★★★★", "★★☆☆☆", "Punch", "https://www.youtube.com/embed/w4Q_G3UwBZE?si=MHU3E2T3nkDVagl8", "https://www.youtube.com/embed/M8GQ_nIf4qg?si=KUCkeQ1QQB1cf9U4");
INSERT INTO strikes (`name`, `power`, `speed`, `strike_type`, `video_url_tutorial`, `video_url_fighter`) VALUES ("Right Kick", "★★★★☆", "★★★★☆", "Kick", "https://www.youtube.com/embed/VT7e0FSwQsI?si=1nBA7EvfGULXDOG2", "https://www.youtube.com/embed/IMAHbYPPPSg?si=8HkruCXK7EEZLOy9");
INSERT INTO strikes (`name`, `power`, `speed`, `strike_type`, `video_url_tutorial`, `video_url_fighter`) VALUES ("Left Kick", "★★★★☆", "★★★★☆", "Kick", "https://www.youtube.com/embed/Hl4xhjTzT08?si=ArwoJD_SEK0GE01N", "https://www.youtube.com/embed/MD3ukY0r4xE?si=QSpjWHWOhWzRjjiH");
INSERT INTO strikes (`name`, `power`, `speed`, `strike_type`, `video_url_tutorial`, `video_url_fighter`) VALUES ("Question Mark Kick", "★★★☆☆", "★★★☆☆", "Kick", "https://www.youtube.com/embed/Po6x3s4mmZc?si=fOUlRgjzqzmaPnEB", "https://www.youtube.com/embed/k1RYdIuNrdM?si=qx06zgXKZ1YnFlfz");
INSERT INTO strikes (`name`, `power`, `speed`, `strike_type`, `video_url_tutorial`, `video_url_fighter`) VALUES ("Teep", "★★★☆☆", "★★★★☆", "Kick", "https://www.youtube.com/embed/5wBQs-l7yss?si=KCpOZZDwb1t3Af_C", "https://www.youtube.com/embed/yFaeg91gbMc?si=kgqaDGJhZIRC9gf-");
INSERT INTO strikes (`name`, `power`, `speed`, `strike_type`, `video_url_tutorial`, `video_url_fighter`) VALUES ("Uppercut", "★★★★☆", "★★★★☆", "Punch", "https://www.youtube.com/embed/eBxn21FtqPg?si=AiDOQ6ly1iiG2yPZ", "https://www.youtube.com/embed/KtET4nnPbtw?si=nhvVvfnbLCImHBe5");

INSERT INTO fighters (`first_name`, `last_name`, `age`, `gym`, `discipline`, `location`, `profile_picture`, `strike1_id`, `strike2_id`, `strike3_id`, `strike4_id` ) VALUES ("Rodtang", "Jitmuangnon", "26", "Jitmuangnon Gym", "Muay Thai", "Bangkok, Thailand", "https://cdn.onefc.com/wp-content/uploads/2018/08/Rodtang_Jitmuangnon-hero-1200x1165-champ-600x583.jpg", "2", "3", "5", "6");
INSERT INTO fighters (`first_name`, `last_name`, `age`, `gym`, `discipline`, `location`, `profile_picture`, `strike1_id`, `strike2_id`, `strike3_id`, `strike4_id` ) VALUES ("Superbon", "Singha Mawynn", "33", "Singha Mawynn Gym", "Muay Thai", "Bangkok, Thailand", "https://cdn.onefc.com/wp-content/uploads/2020/04/Superbon-hero-1200x1165-5-600x583.jpg", "5", "6", "2", "3");
INSERT INTO fighters (`first_name`, `last_name`, `age`, `gym`, `discipline`, `location`, `profile_picture`, `strike1_id`, `strike2_id`, `strike3_id`, `strike4_id` ) VALUES ("Saenchai", "Saepong", "43", "Yokkao Gym", "Muay Thai", "Bangkok, Thailand", "https://cdn.shopify.com/s/files/1/0224/6724/8200/files/saenchai_5d9f3754-c7c2-41a0-a752-475f207c7182.jpg?v=1575626613", "6", "2", "8", "7");
INSERT INTO fighters (`first_name`, `last_name`, `age`, `gym`, `discipline`, `location`, `profile_picture`, `strike1_id`, `strike2_id`, `strike3_id`, `strike4_id` ) VALUES ("Tawanchai", "PK Saenchai", "24", "PK Saenchai Gym", "Muay Thai", "Bangkok, Thailand", "https://cdn.onefc.com/wp-content/uploads/2021/05/Tawanchai-Hero-1200x1165-1-600x583.jpg", "6", "8", "2", "3");
